name: sync

on:
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - closed
      - deleted
      - edited
      - labeled
      - opened
      - pinned
      - reopened
      - transferred
      - unlabeled
      - unpinned

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: data
          ref: data
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec ruby scripts/sync.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cp -r .github data/.github
          ls -la data
      - uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: .
          disable_nojekyll: true
          force_orphan: true
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_branch: data
          publish_dir: data
